apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      name: onboarding-manager
  template:
    metadata:
      labels:
        name: onboarding-manager
    spec:
      serviceAccountName: onboarding-manager
      containers:
        - name: onboarding-manager
          # Replace this with the built image name
          image: quay.io/redhat-cop/onboarding-manager
          command:
          - onboarding-manager
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "onboarding-manager"
