kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sandbox-manager
rules:
- apiGroups:
  - ""
  - user.openshift.io/v1
  resources:
  - users
  verbs:
  - list
  - get
- apiGroups:
  - ""
  - authorization.openshift.io/v1
  resources:
  - namespaces
  - rolebindings
  verbs:
  - get
  - create
